### ISSUE TITLE
Conflict with NyfsQuiver

### ISSUE THREAD

**Issue by awesomedeity** [aschmois/Modified-Anvil#2]
Minecraft V 1.18.1
Forge V 39.0.64
Modified Anvil V 0.01
NyfsQuiver V 0.6.4

The game crashes if you try to load with both mods installed.

**Comment by aschmois** [comment]
This is no longer an issue. Did some investigation and not sure what would cause this conflict but considering it's not crashing anymore should be good.

Might be related to `NyfsQuiver` requiring curios?
